# spring.application.name=bkg-information-management-systems-backend
# # spring.application.name=bkgdbms-backend


# # spring.datasource.url=jdbc:sqlserver://sqlsrv-bkg-dev-gwc-01.database.windows.net:1433;database=sqldb-bkg-dev-gwc-basic-01;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
# # spring.datasource.username=briankamanga@sqlsrv-bkg-dev-gwc-01
# # spring.datasource.password=dexter1983_BKMD

# # spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# # spring.jpa.hibernate.ddl-auto=update
# # spring.jpa.show-sql=true
# # spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


# #spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433/briankamangagroup
# spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
# # spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=briankamangagroup;encrypt=false;trustServerCertificate=false;
# # spring.datasource.url=jdbc:sqlserver://sqlsrv-bkg-dev-gwc-01.database.windows.net;databaseName=sqldb-bkg-dev-gwc-basic-01;encrypt=false;trustServerCertificate=false;

# spring.datasource.url=jdbc:sqlserver://sqlsrv-bkg-dev-gwc-01.database.windows.net:1433;database=sqldb-bkg-dev-gwc-basic-01;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
# spring.datasource.username=briankamanga
# spring.datasource.password=dexter1983_BKMD

# # spring.datasource.username=sa
# # spring.datasource.username=briankamanga
# # spring.datasource.password=dexter1983_BKMD
# # spring.datasource.password=dexter1983_BKMD
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# # next line ensures schema creation during runtime when it is not in the db already - Camel casing is replaced by underscores
# spring.jpa.properties.javax.persistence.create-database-schemas=true

# # ensures camel casing isn't replaced by underscores
# spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


server.port=8090

spring.application.name=bkg-information-management-systems-backend

spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://sqlsrv-bkg-dev-gwc-01.database.windows.net:1433;database=sqldb-bkg-dev-gwc-basic-01;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=briankamanga@sqlsrv-bkg-dev-gwc-01
spring.datasource.password=dexter1983_BKMD
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.javax.persistence.create-database-schemas=true
# spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.open-in-view=false




spring.jpa.properties.hibernate.transaction.coordinator_class=jdbc
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.default_schema=dbo

logging.level.org.hibernate.tool.hbm2ddl=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

